version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - documents_parent:/app/documents/parent
      - documents_child:/app/documents/child
    ports:
      - 8501:8501
    # environment: 
      # - PYTHONUNBUFFERED=1

volumes:
  documents_parent:
  documents_child:

# volumes:
#   documents:
#     driver: local
